/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'timbrooks' at '6/19/15 7:52 PM' with Gradle 2.4
 *
 * @author timbrooks, @date 6/19/15 7:52 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
